addons:
  apt:
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo
install: true
script:
  - ./configure --prefix=/tmp/build-default
  - (make > /dev/null) || (make -j1 && exit 1)
