sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bc
      - bison
      - build-essential
      - curl
      - expect
      - flex
      - gawk
      - gperf
      - libgmp-dev
      - libmpc-dev
      - libmpfr-dev
      - libtool
      - patchutils
      - texinfo
      - gcc-4.8
      - g++-4.8
before_install:
  - export MAKEFLAGS="-j3"
  - export CXX=g++-4.8
  - export CC=gcc-4.8
env:
  - CARGS="--enable-linux  --disable-multilib --with-arch=rv32imac --with-abi=ilp32"
  - CARGS="--enable-linux  --disable-multilib --with-arch=rv32imafdc --with-abi=ilp32"
  - CARGS="--enable-linux  --disable-multilib --with-arch=rv32imafdc --with-abi=ilp32d"
  - CARGS="--enable-linux  --disable-multilib --with-arch=rv64imac --with-abi=lp64"
  - CARGS="--enable-linux  --disable-multilib --with-arch=rv64imafdc --with-abi=lp64"
  - CARGS="--enable-linux  --disable-multilib --with-arch=rv64imafdc --with-abi=lp64d"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32i --with-abi=ilp32"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32im --with-abi=ilp32"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32iac --with-abi=ilp32"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32imac --with-abi=ilp32"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv32imafc --with-abi=ilp32f"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv64imac --with-abi=lp64"
  - CARGS="--disable-linux  --disable-multilib --with-arch=rv64imafdc --with-abi=lp64d"
install: true
script:
  - ./configure --prefix=/tmp/build-default $CARGS
  - travis_wait 90 scripts/wrapper/make_tail
  - travis_wait 45 scripts/wrapper/make_tail check
  - make report
